my_string = input("Введите текст: ")
k = len(my_string)
print(int(k))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])
